apiVersion: v1
appVersion: 2.15.0-jdk11
deprecated: false
description: Apache Ignite is an open-source distributed database, caching
  and processing platform designed to store and compute on large volumes of data across
  a cluster of nodes.
engine: gotpl
home: https://ignite.apache.org/
icon: https://ignite.apache.org/images/Ignite_tm_Logo_wht_RGB.svg
keywords:
- java
- datagrid
- caching
- jvm
- sql
- key-value
- nosql
- distributed
name: ignite
sources:
- https://github.com/apache/ignite
version: 1.2.3
